import React, { useState } from 'react';
import {
  ClipboardList,
  CheckCircle2,
  Clock,
  MapPin,
  Send,
  Users,
  Truck,
  ChevronRight,
} from 'lucide-react';
import { WhyPanel } from '../components/WhyPanel';
import { getEvidenceForZone } from '../data/mockZoneEvidenceData';
import { ZoneEvidenceDetail } from '../types';
import { useTacticalPlanner, TacticalAction } from '../api';
import { getTierConfig } from '../theme/tiers';

export const ResponsePlannerPage: React.FC = () => {
  const { actions, dispatchAction, dispatchAll } = useTacticalPlanner();
  const [selectedZone, setSelectedZone] = useState<ZoneEvidenceDetail | null>(null);
  const [isWhyPanelOpen, setIsWhyPanelOpen] = useState(false);

  const handleOpenWhy = (zoneId: string) => {
    const evidence = getEvidenceForZone(zoneId);
    setSelectedZone(evidence);
    setIsWhyPanelOpen(true);
  };

  const getPriorityBadge = (priority: string) => {
    const tierKey = priority === 'MEDIUM' ? 'MODERATE' : priority;
    const cfg = getTierConfig(tierKey);
    const Icon = cfg.icon;
    return (
      <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] sm:text-[11px] font-bold ${cfg.tintBg} ${cfg.tintText} ${cfg.tintBorder} border uppercase tracking-wider`}>
        <Icon size={11} strokeWidth={2.5} />
        <span>{priority} Priority</span>
      </span>
    );
  };

  return (
    <div id="response-planner-page" className="p-4 sm:p-6 lg:p-8 flex flex-col gap-4 sm:gap-6 max-w-7xl mx-auto">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white border border-[#F1F5F9] rounded-3xl p-4 sm:p-6 shadow-xs">
        <div className="flex items-start sm:items-center gap-3.5 sm:gap-4">
          <div className="w-10 h-10 sm:w-12 sm:h-12 rounded-2xl bg-orange-50 border border-orange-100 flex items-center justify-center text-[#F97316] shrink-0">
            <ClipboardList size={22} strokeWidth={2} />
          </div>
          <div>
            <div className="flex flex-wrap items-center gap-2">
              <h1 className="text-lg sm:text-2xl font-black text-[#0F172A] tracking-tight">
                Autonomous Response & Tactical Planner
              </h1>
              <span className="px-2.5 py-0.5 rounded-full bg-[#FFEDD5] text-[#C2410C] text-[10px] font-bold uppercase tracking-wider">
                {actions.length} Interventions Queued
              </span>
            </div>
            <p className="text-xs sm:text-sm text-[#64748B] mt-0.5">
              Ranked mitigating actions generated by the Heat Hunt agent. Dispatch teams or inspect the WHY evidence justification.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 shrink-0">
          <button
            type="button"
            onClick={dispatchAll}
            className="min-h-[40px] inline-flex items-center justify-center gap-2 px-5 py-2.5 rounded-full bg-[#F97316] hover:bg-[#ea580c] text-white text-xs font-bold focus-visible:ring-2 focus-visible:ring-[#F97316] focus-visible:outline-none transition-all shadow-xs cursor-pointer active:scale-95 w-full sm:w-auto"
          >
            <Send size={14} />
            <span>Dispatch All Queued Units</span>
          </button>
        </div>
      </div>

      {/* Action Cards List */}
      <div className="flex flex-col gap-4 sm:gap-5">
        {actions.map((act: TacticalAction) => (
          <div
            key={act.id}
            id={`tactical-action-${act.id}`}
            className="bg-white border border-[#F1F5F9] rounded-3xl p-4 sm:p-6 shadow-xs flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4 sm:gap-6 hover:border-slate-300 transition-all"
          >
            <div className="flex items-start gap-3.5 sm:gap-4 min-w-0">
              {/* Step Circle */}
              <div className="w-9 h-9 sm:w-10 sm:h-10 rounded-2xl bg-[#0F172A] text-white font-black text-xs sm:text-sm flex items-center justify-center shrink-0 mt-0.5">
                {act.stepNumber}
              </div>

              {/* Action Details */}
              <div className="flex flex-col gap-1.5 min-w-0">
                <div className="flex items-center gap-2 flex-wrap">
                  {getPriorityBadge(act.priority)}
                  <span className="inline-flex items-center gap-1 text-xs font-semibold text-slate-700 bg-slate-50 px-2.5 py-0.5 rounded-full border border-slate-200">
                    <MapPin size={12} className="text-[#EA580C]" />
                    <span>{act.zoneName}</span>
                  </span>
                  <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-slate-100 border border-slate-200 text-slate-600 text-[11px] font-medium">
                    <Clock size={11} className="text-slate-400" />
                    <span>{act.eta}</span>
                  </span>
                </div>

                <h2 className="text-sm sm:text-base font-bold text-[#0F172A] tracking-tight">
                  {act.title}
                </h2>

                <p className="text-xs text-slate-600 leading-relaxed max-w-3xl">
                  {act.description}
                </p>

                {/* Metadata tags */}
                <div className="flex items-center gap-2.5 sm:gap-3 text-xs text-slate-600 mt-2 flex-wrap">
                  <span className="inline-flex items-center gap-1.5 bg-slate-50 px-2.5 py-1 rounded-full border border-slate-200 text-slate-600 font-medium">
                    <Users size={13} className="text-slate-400" />
                    <span>Assigned: <strong className="text-slate-800 font-semibold">{act.assignedTeam}</strong></span>
                  </span>
                  <span className="inline-flex items-center gap-1.5 bg-teal-50 px-2.5 py-1 rounded-full border border-teal-200 text-[#0f766e] font-medium">
                    <span>Impact: <strong className="text-teal-900 font-semibold">{act.impactScore}</strong></span>
                  </span>
                </div>
              </div>
            </div>

            {/* Action Buttons Right */}
            <div className="flex items-center gap-2.5 sm:gap-3 w-full lg:w-auto shrink-0 justify-end pt-3 lg:pt-0 border-t lg:border-t-0 border-slate-100 flex-wrap sm:flex-nowrap">
              <button
                type="button"
                onClick={() => handleOpenWhy(act.zoneId)}
                className="min-h-[38px] flex-1 sm:flex-none inline-flex items-center justify-center gap-1 px-4 py-2 rounded-full border border-slate-200 text-slate-700 hover:bg-slate-50 text-xs font-bold focus-visible:ring-2 focus-visible:ring-[#F97316] focus-visible:outline-none transition-colors cursor-pointer"
              >
                <span>Evidence (WHY)</span>
                <ChevronRight size={14} />
              </button>

              <button
                type="button"
                onClick={() => dispatchAction(act.id)}
                className={`min-h-[38px] flex-1 sm:flex-none inline-flex items-center justify-center gap-1.5 px-5 py-2 rounded-full text-xs font-bold focus-visible:ring-2 focus-visible:ring-[#0D9488] focus-visible:outline-none transition-all shadow-xs cursor-pointer ${
                  act.status === 'Deployed'
                    ? 'bg-emerald-700 text-white'
                    : act.status === 'In Route'
                    ? 'bg-[#EA580C] text-white'
                    : 'bg-[#0D9488] hover:bg-[#0f766e] text-white'
                }`}
              >
                {act.status === 'Deployed' ? (
                  <>
                    <CheckCircle2 size={14} />
                    <span>Deployed</span>
                  </>
                ) : act.status === 'In Route' ? (
                  <>
                    <Truck size={14} />
                    <span>En Route</span>
                  </>
                ) : (
                  <>
                    <Send size={14} />
                    <span>Dispatch Team</span>
                  </>
                )}
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* WHY Evidence Drawer */}
      <WhyPanel
        isOpen={isWhyPanelOpen}
        onClose={() => setIsWhyPanelOpen(false)}
        evidence={selectedZone}
      />
    </div>
  );
};
